[package]
name = "mchprs_network"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hematite-nbt = "0.5"
flate2 = "1"
serde = "1"
byteorder = "1.4"
tracing = "0.1"
